"""initial_schema_20_tables

Revision ID: 0377dbae2d04
Revises: 
Create Date: 2026-03-10 10:19:26.288282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0377dbae2d04'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('meta_ad_account_id', sa.String(length=100), nullable=False),
    sa.Column('business_type', sa.String(length=50), nullable=False),
    sa.Column('target_cpl', sa.Float(), nullable=True),
    sa.Column('target_cpa', sa.Float(), nullable=True),
    sa.Column('target_roas', sa.Float(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('telegram_chat_id', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('settings_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('health_check_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_name', sa.String(length=255), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_check_logs_task_name'), 'health_check_logs', ['task_name'], unique=False)
    op.create_table('market_conditions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('btc_price', sa.Float(), nullable=True),
    sa.Column('btc_7d_change_percent', sa.Float(), nullable=True),
    sa.Column('is_btc_crash', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('condition_json', sa.Text(), nullable=False),
    sa.Column('action_json', sa.Text(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('cooldown_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rules_account_id'), 'rules', ['account_id'], unique=False)
    op.create_table('audience_test_queue',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('audience_name', sa.String(length=255), nullable=False),
    sa.Column('audience_type', sa.String(length=50), nullable=False),
    sa.Column('targeting_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('launched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('killed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('kill_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audience_test_queue_account_id'), 'audience_test_queue', ['account_id'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('meta_campaign_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('objective', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('daily_budget', sa.Float(), nullable=True),
    sa.Column('lifetime_budget', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meta_campaign_id')
    )
    op.create_index(op.f('ix_campaigns_account_id'), 'campaigns', ['account_id'], unique=False)
    op.create_table('competitor_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('competitor_name', sa.String(length=255), nullable=False),
    sa.Column('meta_page_id', sa.String(length=100), nullable=True),
    sa.Column('website_url', sa.String(length=2000), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitor_configs_account_id'), 'competitor_configs', ['account_id'], unique=False)
    op.create_table('seasonality_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('budget_modifier_percent', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seasonality_configs_account_id'), 'seasonality_configs', ['account_id'], unique=False)
    op.create_table('ad_sets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('meta_adset_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('audience_type', sa.String(length=50), nullable=False),
    sa.Column('targeting_json', sa.Text(), nullable=True),
    sa.Column('daily_budget', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meta_adset_id')
    )
    op.create_index(op.f('ix_ad_sets_account_id'), 'ad_sets', ['account_id'], unique=False)
    op.create_index(op.f('ix_ad_sets_campaign_id'), 'ad_sets', ['campaign_id'], unique=False)
    op.create_table('competitor_ads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('competitor_config_id', sa.UUID(), nullable=False),
    sa.Column('creative_url', sa.String(length=2000), nullable=True),
    sa.Column('ad_text', sa.Text(), nullable=True),
    sa.Column('hook_text', sa.Text(), nullable=True),
    sa.Column('estimated_spend_range', sa.String(length=100), nullable=True),
    sa.Column('impression_range', sa.String(length=100), nullable=True),
    sa.Column('hook_type', sa.String(length=50), nullable=True),
    sa.Column('cta_type', sa.String(length=50), nullable=True),
    sa.Column('offer_text', sa.Text(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('ai_analysis_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['competitor_config_id'], ['competitor_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitor_ads_account_id'), 'competitor_ads', ['account_id'], unique=False)
    op.create_index(op.f('ix_competitor_ads_competitor_config_id'), 'competitor_ads', ['competitor_config_id'], unique=False)
    op.create_table('ads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('ad_set_id', sa.UUID(), nullable=False),
    sa.Column('meta_ad_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('creative_url', sa.String(length=2000), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=2000), nullable=True),
    sa.Column('ad_type', sa.String(length=50), nullable=False),
    sa.Column('review_status', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('first_active_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['ad_set_id'], ['ad_sets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meta_ad_id')
    )
    op.create_index(op.f('ix_ads_account_id'), 'ads', ['account_id'], unique=False)
    op.create_index(op.f('ix_ads_ad_set_id'), 'ads', ['ad_set_id'], unique=False)
    op.create_table('action_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('ad_id', sa.UUID(), nullable=True),
    sa.Column('rule_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('is_reversible', sa.Boolean(), nullable=False),
    sa.Column('reversed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('triggered_by', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['ad_id'], ['ads.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_logs_account_id'), 'action_logs', ['account_id'], unique=False)
    op.create_table('ad_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ad_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('spend', sa.Float(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('ctr', sa.Float(), nullable=False),
    sa.Column('cpc', sa.Float(), nullable=False),
    sa.Column('cpm', sa.Float(), nullable=False),
    sa.Column('conversions', sa.Integer(), nullable=False),
    sa.Column('cpl', sa.Float(), nullable=False),
    sa.Column('cpa', sa.Float(), nullable=False),
    sa.Column('frequency', sa.Float(), nullable=False),
    sa.Column('video_view_3s_rate', sa.Float(), nullable=False),
    sa.Column('video_p25', sa.Float(), nullable=False),
    sa.Column('video_p50', sa.Float(), nullable=False),
    sa.Column('video_p75', sa.Float(), nullable=False),
    sa.Column('video_p100', sa.Float(), nullable=False),
    sa.Column('reach', sa.Integer(), nullable=False),
    sa.Column('unique_clicks', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['ad_id'], ['ads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ad_metrics_account_id'), 'ad_metrics', ['account_id'], unique=False)
    op.create_index(op.f('ix_ad_metrics_ad_id'), 'ad_metrics', ['ad_id'], unique=False)
    op.create_index(op.f('ix_ad_metrics_timestamp'), 'ad_metrics', ['timestamp'], unique=False)
    op.create_table('ad_placement_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ad_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('placement', sa.String(length=50), nullable=False),
    sa.Column('spend', sa.Float(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('ctr', sa.Float(), nullable=False),
    sa.Column('conversions', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['ad_id'], ['ads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ad_placement_metrics_account_id'), 'ad_placement_metrics', ['account_id'], unique=False)
    op.create_index(op.f('ix_ad_placement_metrics_ad_id'), 'ad_placement_metrics', ['ad_id'], unique=False)
    op.create_index(op.f('ix_ad_placement_metrics_timestamp'), 'ad_placement_metrics', ['timestamp'], unique=False)
    op.create_table('creative_metadata',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ad_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('hook_type', sa.String(length=50), nullable=True),
    sa.Column('cta_type', sa.String(length=50), nullable=True),
    sa.Column('video_length_seconds', sa.Integer(), nullable=True),
    sa.Column('format', sa.String(length=50), nullable=True),
    sa.Column('first_active_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_fatigued', sa.Boolean(), nullable=False),
    sa.Column('fatigued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto_tagged_by_ai', sa.Boolean(), nullable=False),
    sa.Column('ai_analysis_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['ad_id'], ['ads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ad_id')
    )
    op.create_index(op.f('ix_creative_metadata_account_id'), 'creative_metadata', ['account_id'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('source_campaign_id', sa.UUID(), nullable=True),
    sa.Column('source_ad_id', sa.UUID(), nullable=True),
    sa.Column('source_adset_id', sa.UUID(), nullable=True),
    sa.Column('utm_campaign', sa.String(length=500), nullable=True),
    sa.Column('utm_source', sa.String(length=200), nullable=True),
    sa.Column('utm_medium', sa.String(length=200), nullable=True),
    sa.Column('utm_content', sa.String(length=500), nullable=True),
    sa.Column('utm_term', sa.String(length=500), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['source_ad_id'], ['ads.id'], ),
    sa.ForeignKeyConstraint(['source_adset_id'], ['ad_sets.id'], ),
    sa.ForeignKeyConstraint(['source_campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_account_id'), 'leads', ['account_id'], unique=False)
    op.create_index(op.f('ix_leads_email'), 'leads', ['email'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('event_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_account_id'), 'bookings', ['account_id'], unique=False)
    op.create_index(op.f('ix_bookings_lead_id'), 'bookings', ['lead_id'], unique=False)
    op.create_table('deals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('proposal_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deals_account_id'), 'deals', ['account_id'], unique=False)
    op.create_index(op.f('ix_deals_lead_id'), 'deals', ['lead_id'], unique=False)
    op.create_table('landing_page_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('page_url', sa.String(length=2000), nullable=True),
    sa.Column('utm_campaign', sa.String(length=500), nullable=True),
    sa.Column('utm_source', sa.String(length=200), nullable=True),
    sa.Column('scroll_depth_percent', sa.Float(), nullable=True),
    sa.Column('time_on_page_seconds', sa.Integer(), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('browser', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_landing_page_events_account_id'), 'landing_page_events', ['account_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_account_id'), 'payments', ['account_id'], unique=False)
    op.create_index(op.f('ix_payments_deal_id'), 'payments', ['deal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_deal_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_account_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_landing_page_events_account_id'), table_name='landing_page_events')
    op.drop_table('landing_page_events')
    op.drop_index(op.f('ix_deals_lead_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_account_id'), table_name='deals')
    op.drop_table('deals')
    op.drop_index(op.f('ix_bookings_lead_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_account_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_leads_email'), table_name='leads')
    op.drop_index(op.f('ix_leads_account_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_creative_metadata_account_id'), table_name='creative_metadata')
    op.drop_table('creative_metadata')
    op.drop_index(op.f('ix_ad_placement_metrics_timestamp'), table_name='ad_placement_metrics')
    op.drop_index(op.f('ix_ad_placement_metrics_ad_id'), table_name='ad_placement_metrics')
    op.drop_index(op.f('ix_ad_placement_metrics_account_id'), table_name='ad_placement_metrics')
    op.drop_table('ad_placement_metrics')
    op.drop_index(op.f('ix_ad_metrics_timestamp'), table_name='ad_metrics')
    op.drop_index(op.f('ix_ad_metrics_ad_id'), table_name='ad_metrics')
    op.drop_index(op.f('ix_ad_metrics_account_id'), table_name='ad_metrics')
    op.drop_table('ad_metrics')
    op.drop_index(op.f('ix_action_logs_account_id'), table_name='action_logs')
    op.drop_table('action_logs')
    op.drop_index(op.f('ix_ads_ad_set_id'), table_name='ads')
    op.drop_index(op.f('ix_ads_account_id'), table_name='ads')
    op.drop_table('ads')
    op.drop_index(op.f('ix_competitor_ads_competitor_config_id'), table_name='competitor_ads')
    op.drop_index(op.f('ix_competitor_ads_account_id'), table_name='competitor_ads')
    op.drop_table('competitor_ads')
    op.drop_index(op.f('ix_ad_sets_campaign_id'), table_name='ad_sets')
    op.drop_index(op.f('ix_ad_sets_account_id'), table_name='ad_sets')
    op.drop_table('ad_sets')
    op.drop_index(op.f('ix_seasonality_configs_account_id'), table_name='seasonality_configs')
    op.drop_table('seasonality_configs')
    op.drop_index(op.f('ix_competitor_configs_account_id'), table_name='competitor_configs')
    op.drop_table('competitor_configs')
    op.drop_index(op.f('ix_campaigns_account_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_audience_test_queue_account_id'), table_name='audience_test_queue')
    op.drop_table('audience_test_queue')
    op.drop_index(op.f('ix_rules_account_id'), table_name='rules')
    op.drop_table('rules')
    op.drop_table('market_conditions')
    op.drop_index(op.f('ix_health_check_logs_task_name'), table_name='health_check_logs')
    op.drop_table('health_check_logs')
    op.drop_table('accounts')
    # ### end Alembic commands ###
