"""Reports API — placeholder for Computer-generated reports.

Reports are now generated by Perplexity Computer during scheduled runs.
Computer calls the report data endpoints, generates PDFs, and delivers them.
This module provides the data assembly endpoint Computer uses.
"""

import logging
from uuid import UUID

from fastapi import APIRouter, Depends, Query
from sqlalchemy.ext.asyncio import AsyncSession

from app.database import get_db
from app.services.reports.generator import generate_weekly_report_data

logger = logging.getLogger(__name__)
router = APIRouter()


@router.get("/data")
async def get_report_data(
    account_id: UUID = Query(...),
    db: AsyncSession = Depends(get_db),
):
    """Return structured weekly report data for Computer to consume.

    Perplexity Computer calls this endpoint during scheduled runs,
    then uses the data to generate analysis and PDF reports.
    """
    data = await generate_weekly_report_data(db, account_id)
    return {"data": data}
